repos:
  # Black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
#        entry: py -m black .
        args: ["--line-length=120"]

  # isort
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
#        entry: py -m isort .
        args: ["--profile", "black"]
